[platform.windows.x86_64]
version = "0.4.2"
sha256 = "20ae2e4336aa47208576391a3acc96d237079fcda7faa83c31452baee40e0a66"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-windows-x86_64.zip"

[platform.windows.arm64]
version = "0.4.2"
sha256 = "06439bbd204fc006cd6a3ff27c717b8caf78005e318962d68d2c36e7ee5a0c12"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-windows-arm64.zip"

[platform.linux.appimage.arm64]
version = "0.4.2"
sha256 = "483196666f68fccbc19daf71eb4661c508082cfb37992890cea246bef873804f"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-linux-arm64.AppImage"

[platform.linux.flatpak.arm64]
version = "0.4.2"
sha256 = "4dbc9579358933c4c49b0d4b554acbdd85ce3ca45f2813fbda49955cd99e67fa"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-linux-arm64.flatpak"

[platform.linux.appimage.x86_64]
version = "0.4.2"
sha256 = "0abb1188424519e5f3ec5005257853f5ee6bdeae87551c9034cf2e93d6fd2502"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-linux-x86_64.AppImage"

[platform.linux.flatpak.x86_64]
version = "0.4.2"
sha256 = "e627b610d8f85bd8ad17442ca47980be35568320e4739509da6ba235aee2e052"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-linux-x86_64.flatpak"

[platform.macos.arm64]
version = "0.4.2"
sha256 = "924038aac561482c81c15cfb3eeed9be4de2d45dd6a8aa24cdbd39a4c8c3b475"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-macos-arm64.zip"

[platform.macos.x86_64]
version = "0.4.2"
sha256 = "28f937797f8f11588069035c67e7ff1c57bb837b01abe7528b25a820ee521279"
url = "https://github.com/eosin-platform/eov/releases/download/v0.4.2/eov-v0.4.2-macos-x86_64.zip"

# =================================================================
# Plugins section
# =================================================================

[plugins.annotations]
repository = "https://github.com/eosin-platform/eov-annotations-plugin"
version = "0.2.0"
description = "Official annotations plugin"

[plugins.gamepad]
repository = "https://github.com/eosin-platform/eov-gamepad-plugin"
version = "0.2.1"
description = "Provides support for using gamepads as input devices"
